server:
  port: 8080

spring:
  application:
    name: tennis-pulse

  datasource:
    url: jdbc:postgresql://localhost:5432/tennispulse
    username: tennis
    password: tennis
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # use validate so schema must match Flyway migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false    # good practice for APIs
    show-sql: true        # set to true if you want SQL in the logs

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    # use trace to enable method entry and exit logging for api and service packages
#    com.tennispulse.logging: TRACE