server:
  port: 8080

aws:
  sqs:
    endpoint: http://localhost:4566  # LocalStack edge port
    region: us-east-1

tennispulse:
  sqs:
    match-completed-queue-name: match-completed-queue
    # This will be resolved to URL at startup:
    match-completed-queue-url: ${AWS_SQS_MATCH_COMPLETED_URL:}

spring:
  application:
    name: tennis-pulse

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
        region: us-east-1

  data:
    mongodb:
      uri: mongodb://localhost:27017/tennispulse

  datasource:
    url: jdbc:postgresql://localhost:5432/tennispulse
    username: tennis
    password: tennis
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # use validate so schema must match Flyway migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false    # good practice for APIs
    show-sql: true        # set to true if you want SQL in the logs

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: ERROR
    # use trace to enable method entry and exit logging for api and service packages
#    com.tennispulse.logging: TRACE